[General]
dns_server = 1.1.1.1, 8.8.8.8

[Rule]
# Redirige el tráfico de Garena al script
DOMAIN-keyword, garena, script-path=fenix_script.js
DOMAIN-keyword, cbt, script-path=fenix_script.js

[Script]
# Aquí es donde vinculas el código que me mandaste
fenix_script = type=http-response,pattern=^https?:\/\/dl\.cbt\.garena\.com,requires-body=1,max-size=0,script-path=https://tu-repositorio.vercel.app/fenix_script.js
